### ISSUE TITLE
Improve the quality of log messages

### ISSUE THREAD

**Issue by Fr0d0Beutl1n** [mollyim/mollysocket#12]
## Problem 
I recently installed the server, and had issues with the config (#11), because I specified a wrong database location (?). To be honest, I don't really know what exactly was the issue.

Unfortunately, the log messages didn't really help troubleshooting, and were a bit misleading. When I tried adding a connection, the log message told me, that the connection was successfully added, even though it was not. 

## Proposed Solution
- At startup, check whether the database works, and initate a crash in case it doesn't
- When accessing the database, print a log message with details about the success of the operation

**Comment by fl0bo** [comment]
I might have had a similar issue.
I've put the database in a directory called /var/lib/mollysocket and the systemd unit used here runs mollysocket as part of a corresponding user and group.
In order to run correctly the directory /var/lib/mollysocket requires explicit read access. Only providing access for the group wasn't sufficient, otherwise it paniced with:
Error code 1544: SQLITE_READONLY_DIRECTORY

```
# ls -la /var/lib/mollysocket/
total 20
drwxr-xr-x  2 mollysocket mollysocket  4096 Nov 27 13:12 .
drwxr-xr-x 27 root        root         4096 Nov  3 15:20 ..
-rw-r-----  1 mollysocket mollysocket 12288 Nov 27 13:12 mollysocket.db
```
